# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='domicilio',
            field=models.TextField(default='algo'),
        ),
    ]
